Pnpm migration (#193)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,8 +17,14 @@ commands:
     steps:
       - install_ssh_keys_command
       - run:
+          name: Disable Corepack
+          command: sudo corepack disable
+      - run:
+          name: Install pnpm
+          command: sudo npm i -g pnpm@^10
+      - run:
           name: Install dependencies
-          command: yarn install
+          command: pnpm install
 
   install_ssh_keys_command:
     description: "Install SSH keys"
@@ -83,7 +89,7 @@ jobs:
             CKE5_SLACK_NOTIFY_HIDE_AUTHOR: << parameters.hideAuthor >>
             CKE5_PIPELINE_NUMBER: << pipeline.number >>
           name: Waiting for other jobs to finish and sending notification on failure
-          command: yarn ckeditor5-dev-ci-circle-workflow-notifier
+          command: pnpm ckeditor5-dev-ci-circle-workflow-notifier
           no_output_timeout: 1h
 
   validate_and_tests:
@@ -94,10 +100,10 @@ jobs:
       - bootstrap_repository_command
       - run:
           name: Execute ESLint
-          command: yarn run lint
+          command: pnpm run lint
       - run:
           name: Run unit tests
-          command: yarn run coverage
+          command: pnpm run coverage
       - unless:
           # Upload the code coverage results for non-nightly builds only.
           condition: << pipeline.parameters.isNightly >>
@@ -113,9 +119,15 @@ jobs:
                   then
                     circleci-agent step halt
                   fi
-            - run:
-                name: Upload code coverage
-                command: cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
+      - run:
+          name: Upload code coverage (non-fatal)
+          command: |
+            #!/bin/bash
+
+            set -eo pipefail
+
+            cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js \
+              || echo "Coveralls upload failed (e.g., 504). Continuing without failing CI."
 
   release_prepare:
     docker:
@@ -125,7 +137,7 @@ jobs:
       - bootstrap_repository_command
       - run:
           name: Check if packages are ready to be released
-          command: yarn run release:prepare-packages --verbose --compile-only
+          command: pnpm run release:prepare-packages --verbose --compile-only
 
   trigger_release_process:
     docker:
@@ -154,7 +166,7 @@ jobs:
             CKE5_GITHUB_RELEASE_BRANCH: master
             CKE5_GITHUB_REPOSITORY_SLUG: cksource/mrgit
             CKE5_COMMIT_SHA1: << pipeline.git.revision >>
-          command: yarn ckeditor5-dev-ci-trigger-circle-build
+          command: pnpm ckeditor5-dev-ci-trigger-circle-build
 
   release_project:
     docker:
@@ -186,7 +198,7 @@ jobs:
 
             # Do not fail if the Node script ends with non-zero exit code.
             set +e
-            yarn ckeditor5-dev-ci-is-job-triggered-by-member
+            pnpm ckeditor5-dev-ci-is-job-triggered-by-member
             EXIT_CODE=$( echo $? )
 
             if [ ${EXIT_CODE} -ne 0 ];
@@ -199,7 +211,7 @@ jobs:
           environment:
             CKE5_GITHUB_ORGANIZATION: cksource
             CKE5_GITHUB_REPOSITORY: mrgit
-          command: yarn ckeditor5-dev-ci-circle-disable-auto-cancel-builds
+          command: pnpm ckeditor5-dev-ci-circle-disable-auto-cancel-builds
       - run:
           name: Prepare the new version to release
           command: npm run release:prepare-packages -- --verbose
@@ -211,7 +223,7 @@ jobs:
           environment:
             CKE5_GITHUB_ORGANIZATION: cksource
             CKE5_GITHUB_REPOSITORY: mrgit
-          command: yarn ckeditor5-dev-ci-circle-enable-auto-cancel-builds
+          command: pnpm ckeditor5-dev-ci-circle-enable-auto-cancel-builds
           when: always
       - run:
           name: Pack the "release/" directory (in case of failure)
